[package]
name = "yad"
version = "0.1.0"
authors = ["Peter Cai <peter@typeblog.net>"]

[dependencies]
base64 = "0.9"
bytes = "0.4"
error-chain = "0.12"
futures = "0.1"
http = "0.1"
hyper = "0.12"
hyper-rustls = "0.14"
num_cpus = "1.0"
percent-encoding = "1.0"
terminal_size = "0.1"
tokio = "0.1"